/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import lorgNew.tables.Answers;
import lorgNew.tables.records.AnswersRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnswersDao extends DAOImpl<AnswersRecord, lorgNew.tables.pojos.Answers, Integer> {

    /**
     * Create a new AnswersDao without any configuration
     */
    public AnswersDao() {
        super(Answers.ANSWERS, lorgNew.tables.pojos.Answers.class);
    }

    /**
     * Create a new AnswersDao with an attached configuration
     */
    public AnswersDao(Configuration configuration) {
        super(Answers.ANSWERS, lorgNew.tables.pojos.Answers.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(lorgNew.tables.pojos.Answers object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Answers> fetchById(Integer... values) {
        return fetch(Answers.ANSWERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public lorgNew.tables.pojos.Answers fetchOneById(Integer value) {
        return fetchOne(Answers.ANSWERS.ID, value);
    }

    /**
     * Fetch records that have <code>qsid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Answers> fetchByQsid(Integer... values) {
        return fetch(Answers.ANSWERS.QSID, values);
    }

    /**
     * Fetch records that have <code>userid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Answers> fetchByUserid(Integer... values) {
        return fetch(Answers.ANSWERS.USERID, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Answers> fetchByContent(String... values) {
        return fetch(Answers.ANSWERS.CONTENT, values);
    }

    /**
     * Fetch records that have <code>slug IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Answers> fetchBySlug(String... values) {
        return fetch(Answers.ANSWERS.SLUG, values);
    }

    /**
     * Fetch a unique record that has <code>slug = value</code>
     */
    public lorgNew.tables.pojos.Answers fetchOneBySlug(String value) {
        return fetchOne(Answers.ANSWERS.SLUG, value);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Answers> fetchByStatus(String... values) {
        return fetch(Answers.ANSWERS.STATUS, values);
    }

    /**
     * Fetch records that have <code>mailme IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Answers> fetchByMailme(Byte... values) {
        return fetch(Answers.ANSWERS.MAILME, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Answers> fetchByCreated(Timestamp... values) {
        return fetch(Answers.ANSWERS.CREATED, values);
    }

    /**
     * Fetch records that have <code>updated IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Answers> fetchByUpdated(Timestamp... values) {
        return fetch(Answers.ANSWERS.UPDATED, values);
    }
}
