/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import lorgNew.tables.Closed;
import lorgNew.tables.records.ClosedRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClosedDao extends DAOImpl<ClosedRecord, lorgNew.tables.pojos.Closed, Integer> {

    /**
     * Create a new ClosedDao without any configuration
     */
    public ClosedDao() {
        super(Closed.CLOSED, lorgNew.tables.pojos.Closed.class);
    }

    /**
     * Create a new ClosedDao with an attached configuration
     */
    public ClosedDao(Configuration configuration) {
        super(Closed.CLOSED, lorgNew.tables.pojos.Closed.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(lorgNew.tables.pojos.Closed object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Closed> fetchById(Integer... values) {
        return fetch(Closed.CLOSED.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public lorgNew.tables.pojos.Closed fetchOneById(Integer value) {
        return fetchOne(Closed.CLOSED.ID, value);
    }

    /**
     * Fetch records that have <code>userid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Closed> fetchByUserid(Integer... values) {
        return fetch(Closed.CLOSED.USERID, values);
    }

    /**
     * Fetch records that have <code>qsid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Closed> fetchByQsid(Integer... values) {
        return fetch(Closed.CLOSED.QSID, values);
    }

    /**
     * Fetch records that have <code>duplicate IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Closed> fetchByDuplicate(Byte... values) {
        return fetch(Closed.CLOSED.DUPLICATE, values);
    }

    /**
     * Fetch records that have <code>original_slug IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Closed> fetchByOriginalSlug(String... values) {
        return fetch(Closed.CLOSED.ORIGINAL_SLUG, values);
    }

    /**
     * Fetch records that have <code>reason IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Closed> fetchByReason(String... values) {
        return fetch(Closed.CLOSED.REASON, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Closed> fetchByStatus(String... values) {
        return fetch(Closed.CLOSED.STATUS, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Closed> fetchByCreated(Timestamp... values) {
        return fetch(Closed.CLOSED.CREATED, values);
    }

    /**
     * Fetch records that have <code>updated IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Closed> fetchByUpdated(Timestamp... values) {
        return fetch(Closed.CLOSED.UPDATED, values);
    }
}
