/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import lorgNew.tables.Comments;
import lorgNew.tables.records.CommentsRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentsDao extends DAOImpl<CommentsRecord, lorgNew.tables.pojos.Comments, Integer> {

    /**
     * Create a new CommentsDao without any configuration
     */
    public CommentsDao() {
        super(Comments.COMMENTS, lorgNew.tables.pojos.Comments.class);
    }

    /**
     * Create a new CommentsDao with an attached configuration
     */
    public CommentsDao(Configuration configuration) {
        super(Comments.COMMENTS, lorgNew.tables.pojos.Comments.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(lorgNew.tables.pojos.Comments object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Comments> fetchById(Integer... values) {
        return fetch(Comments.COMMENTS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public lorgNew.tables.pojos.Comments fetchOneById(Integer value) {
        return fetchOne(Comments.COMMENTS.ID, value);
    }

    /**
     * Fetch records that have <code>answid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Comments> fetchByAnswid(Integer... values) {
        return fetch(Comments.COMMENTS.ANSWID, values);
    }

    /**
     * Fetch records that have <code>qsid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Comments> fetchByQsid(Integer... values) {
        return fetch(Comments.COMMENTS.QSID, values);
    }

    /**
     * Fetch records that have <code>comid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Comments> fetchByComid(Integer... values) {
        return fetch(Comments.COMMENTS.COMID, values);
    }

    /**
     * Fetch records that have <code>userid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Comments> fetchByUserid(Integer... values) {
        return fetch(Comments.COMMENTS.USERID, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Comments> fetchByContent(String... values) {
        return fetch(Comments.COMMENTS.CONTENT, values);
    }

    /**
     * Fetch records that have <code>depth IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Comments> fetchByDepth(Integer... values) {
        return fetch(Comments.COMMENTS.DEPTH, values);
    }

    /**
     * Fetch records that have <code>mailme IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Comments> fetchByMailme(Byte... values) {
        return fetch(Comments.COMMENTS.MAILME, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Comments> fetchByCreated(Timestamp... values) {
        return fetch(Comments.COMMENTS.CREATED, values);
    }

    /**
     * Fetch records that have <code>updated IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Comments> fetchByUpdated(Timestamp... values) {
        return fetch(Comments.COMMENTS.UPDATED, values);
    }
}
