/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import lorgNew.tables.FosUser;
import lorgNew.tables.records.FosUserRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FosUserDao extends DAOImpl<FosUserRecord, lorgNew.tables.pojos.FosUser, Integer> {

    /**
     * Create a new FosUserDao without any configuration
     */
    public FosUserDao() {
        super(FosUser.FOS_USER, lorgNew.tables.pojos.FosUser.class);
    }

    /**
     * Create a new FosUserDao with an attached configuration
     */
    public FosUserDao(Configuration configuration) {
        super(FosUser.FOS_USER, lorgNew.tables.pojos.FosUser.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(lorgNew.tables.pojos.FosUser object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchById(Integer... values) {
        return fetch(FosUser.FOS_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public lorgNew.tables.pojos.FosUser fetchOneById(Integer value) {
        return fetchOne(FosUser.FOS_USER.ID, value);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchByUsername(String... values) {
        return fetch(FosUser.FOS_USER.USERNAME, values);
    }

    /**
     * Fetch records that have <code>username_canonical IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchByUsernameCanonical(String... values) {
        return fetch(FosUser.FOS_USER.USERNAME_CANONICAL, values);
    }

    /**
     * Fetch a unique record that has <code>username_canonical = value</code>
     */
    public lorgNew.tables.pojos.FosUser fetchOneByUsernameCanonical(String value) {
        return fetchOne(FosUser.FOS_USER.USERNAME_CANONICAL, value);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchByEmail(String... values) {
        return fetch(FosUser.FOS_USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>email_canonical IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchByEmailCanonical(String... values) {
        return fetch(FosUser.FOS_USER.EMAIL_CANONICAL, values);
    }

    /**
     * Fetch a unique record that has <code>email_canonical = value</code>
     */
    public lorgNew.tables.pojos.FosUser fetchOneByEmailCanonical(String value) {
        return fetchOne(FosUser.FOS_USER.EMAIL_CANONICAL, value);
    }

    /**
     * Fetch records that have <code>enabled IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchByEnabled(Byte... values) {
        return fetch(FosUser.FOS_USER.ENABLED, values);
    }

    /**
     * Fetch records that have <code>salt IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchBySalt(String... values) {
        return fetch(FosUser.FOS_USER.SALT, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchByPassword(String... values) {
        return fetch(FosUser.FOS_USER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>last_login IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchByLastLogin(Timestamp... values) {
        return fetch(FosUser.FOS_USER.LAST_LOGIN, values);
    }

    /**
     * Fetch records that have <code>confirmation_token IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchByConfirmationToken(String... values) {
        return fetch(FosUser.FOS_USER.CONFIRMATION_TOKEN, values);
    }

    /**
     * Fetch a unique record that has <code>confirmation_token = value</code>
     */
    public lorgNew.tables.pojos.FosUser fetchOneByConfirmationToken(String value) {
        return fetchOne(FosUser.FOS_USER.CONFIRMATION_TOKEN, value);
    }

    /**
     * Fetch records that have <code>password_requested_at IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchByPasswordRequestedAt(Timestamp... values) {
        return fetch(FosUser.FOS_USER.PASSWORD_REQUESTED_AT, values);
    }

    /**
     * Fetch records that have <code>roles IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchByRoles(String... values) {
        return fetch(FosUser.FOS_USER.ROLES, values);
    }

    /**
     * Fetch records that have <code>userid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchByUserid(Integer... values) {
        return fetch(FosUser.FOS_USER.USERID, values);
    }

    /**
     * Fetch records that have <code>owner_id IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchByOwnerId(Integer... values) {
        return fetch(FosUser.FOS_USER.OWNER_ID, values);
    }

    /**
     * Fetch records that have <code>is_owner IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchByIsOwner(Byte... values) {
        return fetch(FosUser.FOS_USER.IS_OWNER, values);
    }

    /**
     * Fetch records that have <code>localize IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchByLocalize(String... values) {
        return fetch(FosUser.FOS_USER.LOCALIZE, values);
    }

    /**
     * Fetch records that have <code>slug IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchBySlug(String... values) {
        return fetch(FosUser.FOS_USER.SLUG, values);
    }

    /**
     * Fetch a unique record that has <code>slug = value</code>
     */
    public lorgNew.tables.pojos.FosUser fetchOneBySlug(String value) {
        return fetchOne(FosUser.FOS_USER.SLUG, value);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchByStatus(String... values) {
        return fetch(FosUser.FOS_USER.STATUS, values);
    }

    /**
     * Fetch records that have <code>cropic IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchByCropic(String... values) {
        return fetch(FosUser.FOS_USER.CROPIC, values);
    }

    /**
     * Fetch records that have <code>logo_url IN (values)</code>
     */
    public List<lorgNew.tables.pojos.FosUser> fetchByLogoUrl(String... values) {
        return fetch(FosUser.FOS_USER.LOGO_URL, values);
    }
}
