/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import lorgNew.tables.LoggerActions;
import lorgNew.tables.records.LoggerActionsRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoggerActionsDao extends DAOImpl<LoggerActionsRecord, lorgNew.tables.pojos.LoggerActions, Integer> {

    /**
     * Create a new LoggerActionsDao without any configuration
     */
    public LoggerActionsDao() {
        super(LoggerActions.LOGGER_ACTIONS, lorgNew.tables.pojos.LoggerActions.class);
    }

    /**
     * Create a new LoggerActionsDao with an attached configuration
     */
    public LoggerActionsDao(Configuration configuration) {
        super(LoggerActions.LOGGER_ACTIONS, lorgNew.tables.pojos.LoggerActions.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(lorgNew.tables.pojos.LoggerActions object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<lorgNew.tables.pojos.LoggerActions> fetchById(Integer... values) {
        return fetch(LoggerActions.LOGGER_ACTIONS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public lorgNew.tables.pojos.LoggerActions fetchOneById(Integer value) {
        return fetchOne(LoggerActions.LOGGER_ACTIONS.ID, value);
    }

    /**
     * Fetch records that have <code>action IN (values)</code>
     */
    public List<lorgNew.tables.pojos.LoggerActions> fetchByAction(String... values) {
        return fetch(LoggerActions.LOGGER_ACTIONS.ACTION, values);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<lorgNew.tables.pojos.LoggerActions> fetchByTitle(String... values) {
        return fetch(LoggerActions.LOGGER_ACTIONS.TITLE, values);
    }
}
