/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import lorgNew.tables.Permissions;
import lorgNew.tables.records.PermissionsRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionsDao extends DAOImpl<PermissionsRecord, lorgNew.tables.pojos.Permissions, Integer> {

    /**
     * Create a new PermissionsDao without any configuration
     */
    public PermissionsDao() {
        super(Permissions.PERMISSIONS, lorgNew.tables.pojos.Permissions.class);
    }

    /**
     * Create a new PermissionsDao with an attached configuration
     */
    public PermissionsDao(Configuration configuration) {
        super(Permissions.PERMISSIONS, lorgNew.tables.pojos.Permissions.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(lorgNew.tables.pojos.Permissions object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Permissions> fetchById(Integer... values) {
        return fetch(Permissions.PERMISSIONS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public lorgNew.tables.pojos.Permissions fetchOneById(Integer value) {
        return fetchOne(Permissions.PERMISSIONS.ID, value);
    }

    /**
     * Fetch records that have <code>roleid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Permissions> fetchByRoleid(Integer... values) {
        return fetch(Permissions.PERMISSIONS.ROLEID, values);
    }

    /**
     * Fetch records that have <code>routeid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Permissions> fetchByRouteid(Integer... values) {
        return fetch(Permissions.PERMISSIONS.ROUTEID, values);
    }

    /**
     * Fetch records that have <code>permit IN (values)</code>
     */
    public List<lorgNew.tables.pojos.Permissions> fetchByPermit(Byte... values) {
        return fetch(Permissions.PERMISSIONS.PERMIT, values);
    }
}
