/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import lorgNew.tables.SeoProfile;
import lorgNew.tables.records.SeoProfileRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeoProfileDao extends DAOImpl<SeoProfileRecord, lorgNew.tables.pojos.SeoProfile, Integer> {

    /**
     * Create a new SeoProfileDao without any configuration
     */
    public SeoProfileDao() {
        super(SeoProfile.SEO_PROFILE, lorgNew.tables.pojos.SeoProfile.class);
    }

    /**
     * Create a new SeoProfileDao with an attached configuration
     */
    public SeoProfileDao(Configuration configuration) {
        super(SeoProfile.SEO_PROFILE, lorgNew.tables.pojos.SeoProfile.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(lorgNew.tables.pojos.SeoProfile object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchById(Integer... values) {
        return fetch(SeoProfile.SEO_PROFILE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public lorgNew.tables.pojos.SeoProfile fetchOneById(Integer value) {
        return fetchOne(SeoProfile.SEO_PROFILE.ID, value);
    }

    /**
     * Fetch records that have <code>qsid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByQsid(Integer... values) {
        return fetch(SeoProfile.SEO_PROFILE.QSID, values);
    }

    /**
     * Fetch records that have <code>tpid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByTpid(Integer... values) {
        return fetch(SeoProfile.SEO_PROFILE.TPID, values);
    }

    /**
     * Fetch records that have <code>auto_alias IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByAutoAlias(Byte... values) {
        return fetch(SeoProfile.SEO_PROFILE.AUTO_ALIAS, values);
    }

    /**
     * Fetch records that have <code>url_canonical IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByUrlCanonical(String... values) {
        return fetch(SeoProfile.SEO_PROFILE.URL_CANONICAL, values);
    }

    /**
     * Fetch records that have <code>meta_title IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByMetaTitle(String... values) {
        return fetch(SeoProfile.SEO_PROFILE.META_TITLE, values);
    }

    /**
     * Fetch records that have <code>meta_description IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByMetaDescription(String... values) {
        return fetch(SeoProfile.SEO_PROFILE.META_DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>graph_page_url IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByGraphPageUrl(String... values) {
        return fetch(SeoProfile.SEO_PROFILE.GRAPH_PAGE_URL, values);
    }

    /**
     * Fetch records that have <code>graph_content_title IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByGraphContentTitle(String... values) {
        return fetch(SeoProfile.SEO_PROFILE.GRAPH_CONTENT_TITLE, values);
    }

    /**
     * Fetch records that have <code>graph_content_description IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByGraphContentDescription(String... values) {
        return fetch(SeoProfile.SEO_PROFILE.GRAPH_CONTENT_DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>graph_content_data IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByGraphContentData(String... values) {
        return fetch(SeoProfile.SEO_PROFILE.GRAPH_CONTENT_DATA, values);
    }

    /**
     * Fetch records that have <code>graph_article_data IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByGraphArticleData(String... values) {
        return fetch(SeoProfile.SEO_PROFILE.GRAPH_ARTICLE_DATA, values);
    }

    /**
     * Fetch records that have <code>hrefland_default_location IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByHreflandDefaultLocation(String... values) {
        return fetch(SeoProfile.SEO_PROFILE.HREFLAND_DEFAULT_LOCATION, values);
    }

    /**
     * Fetch records that have <code>hrefland_for_english IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByHreflandForEnglish(String... values) {
        return fetch(SeoProfile.SEO_PROFILE.HREFLAND_FOR_ENGLISH, values);
    }

    /**
     * Fetch records that have <code>hrefland_for_spanish IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByHreflandForSpanish(String... values) {
        return fetch(SeoProfile.SEO_PROFILE.HREFLAND_FOR_SPANISH, values);
    }

    /**
     * Fetch records that have <code>hrefland_for_korean IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByHreflandForKorean(String... values) {
        return fetch(SeoProfile.SEO_PROFILE.HREFLAND_FOR_KOREAN, values);
    }

    /**
     * Fetch records that have <code>hrefland_for_japanese IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByHreflandForJapanese(String... values) {
        return fetch(SeoProfile.SEO_PROFILE.HREFLAND_FOR_JAPANESE, values);
    }

    /**
     * Fetch records that have <code>robots_allow_search_to_index IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByRobotsAllowSearchToIndex(Byte... values) {
        return fetch(SeoProfile.SEO_PROFILE.ROBOTS_ALLOW_SEARCH_TO_INDEX, values);
    }

    /**
     * Fetch records that have <code>robots_allow_search_to_follow IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByRobotsAllowSearchToFollow(Byte... values) {
        return fetch(SeoProfile.SEO_PROFILE.ROBOTS_ALLOW_SEARCH_TO_FOLLOW, values);
    }

    /**
     * Fetch records that have <code>robots_prevents_search_from_index IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByRobotsPreventsSearchFromIndex(Byte... values) {
        return fetch(SeoProfile.SEO_PROFILE.ROBOTS_PREVENTS_SEARCH_FROM_INDEX, values);
    }

    /**
     * Fetch records that have <code>robots_prevents_search_from_follow IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByRobotsPreventsSearchFromFollow(Byte... values) {
        return fetch(SeoProfile.SEO_PROFILE.ROBOTS_PREVENTS_SEARCH_FROM_FOLLOW, values);
    }

    /**
     * Fetch records that have <code>robots_prevents_cached IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByRobotsPreventsCached(Byte... values) {
        return fetch(SeoProfile.SEO_PROFILE.ROBOTS_PREVENTS_CACHED, values);
    }

    /**
     * Fetch records that have <code>robots_prevents_descriptoin_from IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByRobotsPreventsDescriptoinFrom(Byte... values) {
        return fetch(SeoProfile.SEO_PROFILE.ROBOTS_PREVENTS_DESCRIPTOIN_FROM, values);
    }

    /**
     * Fetch records that have <code>sitemap_frequency IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchBySitemapFrequency(String... values) {
        return fetch(SeoProfile.SEO_PROFILE.SITEMAP_FREQUENCY, values);
    }

    /**
     * Fetch records that have <code>sitemap_priority IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchBySitemapPriority(Double... values) {
        return fetch(SeoProfile.SEO_PROFILE.SITEMAP_PRIORITY, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByCreated(Timestamp... values) {
        return fetch(SeoProfile.SEO_PROFILE.CREATED, values);
    }

    /**
     * Fetch records that have <code>updated IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoProfile> fetchByUpdated(Timestamp... values) {
        return fetch(SeoProfile.SEO_PROFILE.UPDATED, values);
    }
}
