/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import lorgNew.tables.SeoRedirect;
import lorgNew.tables.records.SeoRedirectRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeoRedirectDao extends DAOImpl<SeoRedirectRecord, lorgNew.tables.pojos.SeoRedirect, Integer> {

    /**
     * Create a new SeoRedirectDao without any configuration
     */
    public SeoRedirectDao() {
        super(SeoRedirect.SEO_REDIRECT, lorgNew.tables.pojos.SeoRedirect.class);
    }

    /**
     * Create a new SeoRedirectDao with an attached configuration
     */
    public SeoRedirectDao(Configuration configuration) {
        super(SeoRedirect.SEO_REDIRECT, lorgNew.tables.pojos.SeoRedirect.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(lorgNew.tables.pojos.SeoRedirect object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoRedirect> fetchById(Integer... values) {
        return fetch(SeoRedirect.SEO_REDIRECT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public lorgNew.tables.pojos.SeoRedirect fetchOneById(Integer value) {
        return fetchOne(SeoRedirect.SEO_REDIRECT.ID, value);
    }

    /**
     * Fetch records that have <code>qsid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoRedirect> fetchByQsid(Integer... values) {
        return fetch(SeoRedirect.SEO_REDIRECT.QSID, values);
    }

    /**
     * Fetch records that have <code>tpid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoRedirect> fetchByTpid(Integer... values) {
        return fetch(SeoRedirect.SEO_REDIRECT.TPID, values);
    }

    /**
     * Fetch records that have <code>new_alias IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoRedirect> fetchByNewAlias(String... values) {
        return fetch(SeoRedirect.SEO_REDIRECT.NEW_ALIAS, values);
    }

    /**
     * Fetch records that have <code>old_alias IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoRedirect> fetchByOldAlias(String... values) {
        return fetch(SeoRedirect.SEO_REDIRECT.OLD_ALIAS, values);
    }

    /**
     * Fetch records that have <code>new_segment IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoRedirect> fetchByNewSegment(String... values) {
        return fetch(SeoRedirect.SEO_REDIRECT.NEW_SEGMENT, values);
    }

    /**
     * Fetch records that have <code>old_segment IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoRedirect> fetchByOldSegment(String... values) {
        return fetch(SeoRedirect.SEO_REDIRECT.OLD_SEGMENT, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoRedirect> fetchByType(String... values) {
        return fetch(SeoRedirect.SEO_REDIRECT.TYPE, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoRedirect> fetchByStatus(Byte... values) {
        return fetch(SeoRedirect.SEO_REDIRECT.STATUS, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoRedirect> fetchByCreated(Timestamp... values) {
        return fetch(SeoRedirect.SEO_REDIRECT.CREATED, values);
    }

    /**
     * Fetch records that have <code>updated IN (values)</code>
     */
    public List<lorgNew.tables.pojos.SeoRedirect> fetchByUpdated(Timestamp... values) {
        return fetch(SeoRedirect.SEO_REDIRECT.UPDATED, values);
    }
}
