/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import lorgNew.tables.UserToVotes;
import lorgNew.tables.records.UserToVotesRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserToVotesDao extends DAOImpl<UserToVotesRecord, lorgNew.tables.pojos.UserToVotes, Integer> {

    /**
     * Create a new UserToVotesDao without any configuration
     */
    public UserToVotesDao() {
        super(UserToVotes.USER_TO_VOTES, lorgNew.tables.pojos.UserToVotes.class);
    }

    /**
     * Create a new UserToVotesDao with an attached configuration
     */
    public UserToVotesDao(Configuration configuration) {
        super(UserToVotes.USER_TO_VOTES, lorgNew.tables.pojos.UserToVotes.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(lorgNew.tables.pojos.UserToVotes object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<lorgNew.tables.pojos.UserToVotes> fetchById(Integer... values) {
        return fetch(UserToVotes.USER_TO_VOTES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public lorgNew.tables.pojos.UserToVotes fetchOneById(Integer value) {
        return fetchOne(UserToVotes.USER_TO_VOTES.ID, value);
    }

    /**
     * Fetch records that have <code>usid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.UserToVotes> fetchByUsid(Integer... values) {
        return fetch(UserToVotes.USER_TO_VOTES.USID, values);
    }

    /**
     * Fetch records that have <code>qsid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.UserToVotes> fetchByQsid(Integer... values) {
        return fetch(UserToVotes.USER_TO_VOTES.QSID, values);
    }

    /**
     * Fetch records that have <code>answid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.UserToVotes> fetchByAnswid(Integer... values) {
        return fetch(UserToVotes.USER_TO_VOTES.ANSWID, values);
    }

    /**
     * Fetch records that have <code>comid IN (values)</code>
     */
    public List<lorgNew.tables.pojos.UserToVotes> fetchByComid(Integer... values) {
        return fetch(UserToVotes.USER_TO_VOTES.COMID, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<lorgNew.tables.pojos.UserToVotes> fetchByType(String... values) {
        return fetch(UserToVotes.USER_TO_VOTES.TYPE, values);
    }
}
