/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import lorgNew.Indexes;
import lorgNew.Keys;
import lorgNew.Lorgnew;
import lorgNew.tables.records.SeoProfileRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeoProfile extends TableImpl<SeoProfileRecord> {

    private static final long serialVersionUID = -543381479;

    /**
     * The reference instance of <code>lorgNew.seo_profile</code>
     */
    public static final SeoProfile SEO_PROFILE = new SeoProfile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SeoProfileRecord> getRecordType() {
        return SeoProfileRecord.class;
    }

    /**
     * The column <code>lorgNew.seo_profile.id</code>.
     */
    public final TableField<SeoProfileRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>lorgNew.seo_profile.qsid</code>.
     */
    public final TableField<SeoProfileRecord, Integer> QSID = createField("qsid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>lorgNew.seo_profile.tpid</code>.
     */
    public final TableField<SeoProfileRecord, Integer> TPID = createField("tpid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>lorgNew.seo_profile.auto_alias</code>.
     */
    public final TableField<SeoProfileRecord, Byte> AUTO_ALIAS = createField("auto_alias", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>lorgNew.seo_profile.url_canonical</code>.
     */
    public final TableField<SeoProfileRecord, String> URL_CANONICAL = createField("url_canonical", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lorgNew.seo_profile.meta_title</code>.
     */
    public final TableField<SeoProfileRecord, String> META_TITLE = createField("meta_title", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lorgNew.seo_profile.meta_description</code>.
     */
    public final TableField<SeoProfileRecord, String> META_DESCRIPTION = createField("meta_description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lorgNew.seo_profile.graph_page_url</code>.
     */
    public final TableField<SeoProfileRecord, String> GRAPH_PAGE_URL = createField("graph_page_url", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lorgNew.seo_profile.graph_content_title</code>.
     */
    public final TableField<SeoProfileRecord, String> GRAPH_CONTENT_TITLE = createField("graph_content_title", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lorgNew.seo_profile.graph_content_description</code>.
     */
    public final TableField<SeoProfileRecord, String> GRAPH_CONTENT_DESCRIPTION = createField("graph_content_description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lorgNew.seo_profile.graph_content_data</code>.
     */
    public final TableField<SeoProfileRecord, String> GRAPH_CONTENT_DATA = createField("graph_content_data", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lorgNew.seo_profile.graph_article_data</code>.
     */
    public final TableField<SeoProfileRecord, String> GRAPH_ARTICLE_DATA = createField("graph_article_data", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lorgNew.seo_profile.hrefland_default_location</code>.
     */
    public final TableField<SeoProfileRecord, String> HREFLAND_DEFAULT_LOCATION = createField("hrefland_default_location", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lorgNew.seo_profile.hrefland_for_english</code>.
     */
    public final TableField<SeoProfileRecord, String> HREFLAND_FOR_ENGLISH = createField("hrefland_for_english", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lorgNew.seo_profile.hrefland_for_spanish</code>.
     */
    public final TableField<SeoProfileRecord, String> HREFLAND_FOR_SPANISH = createField("hrefland_for_spanish", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lorgNew.seo_profile.hrefland_for_korean</code>.
     */
    public final TableField<SeoProfileRecord, String> HREFLAND_FOR_KOREAN = createField("hrefland_for_korean", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lorgNew.seo_profile.hrefland_for_japanese</code>.
     */
    public final TableField<SeoProfileRecord, String> HREFLAND_FOR_JAPANESE = createField("hrefland_for_japanese", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lorgNew.seo_profile.robots_allow_search_to_index</code>.
     */
    public final TableField<SeoProfileRecord, Byte> ROBOTS_ALLOW_SEARCH_TO_INDEX = createField("robots_allow_search_to_index", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>lorgNew.seo_profile.robots_allow_search_to_follow</code>.
     */
    public final TableField<SeoProfileRecord, Byte> ROBOTS_ALLOW_SEARCH_TO_FOLLOW = createField("robots_allow_search_to_follow", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>lorgNew.seo_profile.robots_prevents_search_from_index</code>.
     */
    public final TableField<SeoProfileRecord, Byte> ROBOTS_PREVENTS_SEARCH_FROM_INDEX = createField("robots_prevents_search_from_index", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>lorgNew.seo_profile.robots_prevents_search_from_follow</code>.
     */
    public final TableField<SeoProfileRecord, Byte> ROBOTS_PREVENTS_SEARCH_FROM_FOLLOW = createField("robots_prevents_search_from_follow", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>lorgNew.seo_profile.robots_prevents_cached</code>.
     */
    public final TableField<SeoProfileRecord, Byte> ROBOTS_PREVENTS_CACHED = createField("robots_prevents_cached", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>lorgNew.seo_profile.robots_prevents_descriptoin_from</code>.
     */
    public final TableField<SeoProfileRecord, Byte> ROBOTS_PREVENTS_DESCRIPTOIN_FROM = createField("robots_prevents_descriptoin_from", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>lorgNew.seo_profile.sitemap_frequency</code>.
     */
    public final TableField<SeoProfileRecord, String> SITEMAP_FREQUENCY = createField("sitemap_frequency", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lorgNew.seo_profile.sitemap_priority</code>.
     */
    public final TableField<SeoProfileRecord, Double> SITEMAP_PRIORITY = createField("sitemap_priority", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>lorgNew.seo_profile.created</code>.
     */
    public final TableField<SeoProfileRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>lorgNew.seo_profile.updated</code>.
     */
    public final TableField<SeoProfileRecord, Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>lorgNew.seo_profile</code> table reference
     */
    public SeoProfile() {
        this(DSL.name("seo_profile"), null);
    }

    /**
     * Create an aliased <code>lorgNew.seo_profile</code> table reference
     */
    public SeoProfile(String alias) {
        this(DSL.name(alias), SEO_PROFILE);
    }

    /**
     * Create an aliased <code>lorgNew.seo_profile</code> table reference
     */
    public SeoProfile(Name alias) {
        this(alias, SEO_PROFILE);
    }

    private SeoProfile(Name alias, Table<SeoProfileRecord> aliased) {
        this(alias, aliased, null);
    }

    private SeoProfile(Name alias, Table<SeoProfileRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lorgnew.LORGNEW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SEO_PROFILE_IDX_286E90445A90BB43, Indexes.SEO_PROFILE_IDX_286E90446F08F528, Indexes.SEO_PROFILE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SeoProfileRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SEO_PROFILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SeoProfileRecord> getPrimaryKey() {
        return Keys.KEY_SEO_PROFILE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SeoProfileRecord>> getKeys() {
        return Arrays.<UniqueKey<SeoProfileRecord>>asList(Keys.KEY_SEO_PROFILE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoProfile as(String alias) {
        return new SeoProfile(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoProfile as(Name alias) {
        return new SeoProfile(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SeoProfile rename(String name) {
        return new SeoProfile(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SeoProfile rename(Name name) {
        return new SeoProfile(name, null);
    }
}
