/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import lorgNew.Indexes;
import lorgNew.Keys;
import lorgNew.Lorgnew;
import lorgNew.tables.records.SeoRedirectRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeoRedirect extends TableImpl<SeoRedirectRecord> {

    private static final long serialVersionUID = 1981686461;

    /**
     * The reference instance of <code>lorgNew.seo_redirect</code>
     */
    public static final SeoRedirect SEO_REDIRECT = new SeoRedirect();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SeoRedirectRecord> getRecordType() {
        return SeoRedirectRecord.class;
    }

    /**
     * The column <code>lorgNew.seo_redirect.id</code>.
     */
    public final TableField<SeoRedirectRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>lorgNew.seo_redirect.qsid</code>.
     */
    public final TableField<SeoRedirectRecord, Integer> QSID = createField("qsid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>lorgNew.seo_redirect.tpid</code>.
     */
    public final TableField<SeoRedirectRecord, Integer> TPID = createField("tpid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>lorgNew.seo_redirect.new_alias</code>.
     */
    public final TableField<SeoRedirectRecord, String> NEW_ALIAS = createField("new_alias", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lorgNew.seo_redirect.old_alias</code>.
     */
    public final TableField<SeoRedirectRecord, String> OLD_ALIAS = createField("old_alias", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>lorgNew.seo_redirect.new_segment</code>.
     */
    public final TableField<SeoRedirectRecord, String> NEW_SEGMENT = createField("new_segment", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>lorgNew.seo_redirect.old_segment</code>.
     */
    public final TableField<SeoRedirectRecord, String> OLD_SEGMENT = createField("old_segment", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>lorgNew.seo_redirect.type</code>.
     */
    public final TableField<SeoRedirectRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>lorgNew.seo_redirect.status</code>.
     */
    public final TableField<SeoRedirectRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>lorgNew.seo_redirect.created</code>.
     */
    public final TableField<SeoRedirectRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>lorgNew.seo_redirect.updated</code>.
     */
    public final TableField<SeoRedirectRecord, Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>lorgNew.seo_redirect</code> table reference
     */
    public SeoRedirect() {
        this(DSL.name("seo_redirect"), null);
    }

    /**
     * Create an aliased <code>lorgNew.seo_redirect</code> table reference
     */
    public SeoRedirect(String alias) {
        this(DSL.name(alias), SEO_REDIRECT);
    }

    /**
     * Create an aliased <code>lorgNew.seo_redirect</code> table reference
     */
    public SeoRedirect(Name alias) {
        this(alias, SEO_REDIRECT);
    }

    private SeoRedirect(Name alias, Table<SeoRedirectRecord> aliased) {
        this(alias, aliased, null);
    }

    private SeoRedirect(Name alias, Table<SeoRedirectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lorgnew.LORGNEW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SEO_REDIRECT_IDX_22AB3F095A90BB43, Indexes.SEO_REDIRECT_IDX_22AB3F096F08F528, Indexes.SEO_REDIRECT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SeoRedirectRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SEO_REDIRECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SeoRedirectRecord> getPrimaryKey() {
        return Keys.KEY_SEO_REDIRECT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SeoRedirectRecord>> getKeys() {
        return Arrays.<UniqueKey<SeoRedirectRecord>>asList(Keys.KEY_SEO_REDIRECT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoRedirect as(String alias) {
        return new SeoRedirect(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoRedirect as(Name alias) {
        return new SeoRedirect(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SeoRedirect rename(String name) {
        return new SeoRedirect(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SeoRedirect rename(Name name) {
        return new SeoRedirect(name, null);
    }
}
