/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import lorgNew.Indexes;
import lorgNew.Keys;
import lorgNew.Lorgnew;
import lorgNew.tables.records.UserToFavoritesRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserToFavorites extends TableImpl<UserToFavoritesRecord> {

    private static final long serialVersionUID = -74389124;

    /**
     * The reference instance of <code>lorgNew.user_to_favorites</code>
     */
    public static final UserToFavorites USER_TO_FAVORITES = new UserToFavorites();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserToFavoritesRecord> getRecordType() {
        return UserToFavoritesRecord.class;
    }

    /**
     * The column <code>lorgNew.user_to_favorites.id</code>.
     */
    public final TableField<UserToFavoritesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>lorgNew.user_to_favorites.usid</code>.
     */
    public final TableField<UserToFavoritesRecord, Integer> USID = createField("usid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>lorgNew.user_to_favorites.qsid</code>.
     */
    public final TableField<UserToFavoritesRecord, Integer> QSID = createField("qsid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>lorgNew.user_to_favorites.answid</code>.
     */
    public final TableField<UserToFavoritesRecord, Integer> ANSWID = createField("answid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>lorgNew.user_to_favorites.usidfav</code>.
     */
    public final TableField<UserToFavoritesRecord, Integer> USIDFAV = createField("usidfav", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>lorgNew.user_to_favorites.topid</code>.
     */
    public final TableField<UserToFavoritesRecord, Integer> TOPID = createField("topid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>lorgNew.user_to_favorites</code> table reference
     */
    public UserToFavorites() {
        this(DSL.name("user_to_favorites"), null);
    }

    /**
     * Create an aliased <code>lorgNew.user_to_favorites</code> table reference
     */
    public UserToFavorites(String alias) {
        this(DSL.name(alias), USER_TO_FAVORITES);
    }

    /**
     * Create an aliased <code>lorgNew.user_to_favorites</code> table reference
     */
    public UserToFavorites(Name alias) {
        this(alias, USER_TO_FAVORITES);
    }

    private UserToFavorites(Name alias, Table<UserToFavoritesRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserToFavorites(Name alias, Table<UserToFavoritesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lorgnew.LORGNEW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER_TO_FAVORITES_IDX_5506CB863244BB8, Indexes.USER_TO_FAVORITES_IDX_5506CB865A90BB43, Indexes.USER_TO_FAVORITES_IDX_5506CB867361388, Indexes.USER_TO_FAVORITES_IDX_5506CB8682BCB078, Indexes.USER_TO_FAVORITES_IDX_5506CB86D5F22C14, Indexes.USER_TO_FAVORITES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserToFavoritesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USER_TO_FAVORITES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserToFavoritesRecord> getPrimaryKey() {
        return Keys.KEY_USER_TO_FAVORITES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserToFavoritesRecord>> getKeys() {
        return Arrays.<UniqueKey<UserToFavoritesRecord>>asList(Keys.KEY_USER_TO_FAVORITES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserToFavorites as(String alias) {
        return new UserToFavorites(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserToFavorites as(Name alias) {
        return new UserToFavorites(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserToFavorites rename(String name) {
        return new UserToFavorites(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserToFavorites rename(Name name) {
        return new UserToFavorites(name, null);
    }
}
