/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Answers implements Serializable {

    private static final long serialVersionUID = -955310083;

    private Integer   id;
    private Integer   qsid;
    private Integer   userid;
    private String    content;
    private String    slug;
    private String    status;
    private Byte      mailme;
    private Timestamp created;
    private Timestamp updated;

    public Answers() {}

    public Answers(Answers value) {
        this.id = value.id;
        this.qsid = value.qsid;
        this.userid = value.userid;
        this.content = value.content;
        this.slug = value.slug;
        this.status = value.status;
        this.mailme = value.mailme;
        this.created = value.created;
        this.updated = value.updated;
    }

    public Answers(
        Integer   id,
        Integer   qsid,
        Integer   userid,
        String    content,
        String    slug,
        String    status,
        Byte      mailme,
        Timestamp created,
        Timestamp updated
    ) {
        this.id = id;
        this.qsid = qsid;
        this.userid = userid;
        this.content = content;
        this.slug = slug;
        this.status = status;
        this.mailme = mailme;
        this.created = created;
        this.updated = updated;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getQsid() {
        return this.qsid;
    }

    public void setQsid(Integer qsid) {
        this.qsid = qsid;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getSlug() {
        return this.slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Byte getMailme() {
        return this.mailme;
    }

    public void setMailme(Byte mailme) {
        this.mailme = mailme;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Timestamp getUpdated() {
        return this.updated;
    }

    public void setUpdated(Timestamp updated) {
        this.updated = updated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Answers (");

        sb.append(id);
        sb.append(", ").append(qsid);
        sb.append(", ").append(userid);
        sb.append(", ").append(content);
        sb.append(", ").append(slug);
        sb.append(", ").append(status);
        sb.append(", ").append(mailme);
        sb.append(", ").append(created);
        sb.append(", ").append(updated);

        sb.append(")");
        return sb.toString();
    }
}
