/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Closed implements Serializable {

    private static final long serialVersionUID = -1213491679;

    private Integer   id;
    private Integer   userid;
    private Integer   qsid;
    private Byte      duplicate;
    private String    originalSlug;
    private String    reason;
    private String    status;
    private Timestamp created;
    private Timestamp updated;

    public Closed() {}

    public Closed(Closed value) {
        this.id = value.id;
        this.userid = value.userid;
        this.qsid = value.qsid;
        this.duplicate = value.duplicate;
        this.originalSlug = value.originalSlug;
        this.reason = value.reason;
        this.status = value.status;
        this.created = value.created;
        this.updated = value.updated;
    }

    public Closed(
        Integer   id,
        Integer   userid,
        Integer   qsid,
        Byte      duplicate,
        String    originalSlug,
        String    reason,
        String    status,
        Timestamp created,
        Timestamp updated
    ) {
        this.id = id;
        this.userid = userid;
        this.qsid = qsid;
        this.duplicate = duplicate;
        this.originalSlug = originalSlug;
        this.reason = reason;
        this.status = status;
        this.created = created;
        this.updated = updated;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public Integer getQsid() {
        return this.qsid;
    }

    public void setQsid(Integer qsid) {
        this.qsid = qsid;
    }

    public Byte getDuplicate() {
        return this.duplicate;
    }

    public void setDuplicate(Byte duplicate) {
        this.duplicate = duplicate;
    }

    public String getOriginalSlug() {
        return this.originalSlug;
    }

    public void setOriginalSlug(String originalSlug) {
        this.originalSlug = originalSlug;
    }

    public String getReason() {
        return this.reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Timestamp getUpdated() {
        return this.updated;
    }

    public void setUpdated(Timestamp updated) {
        this.updated = updated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Closed (");

        sb.append(id);
        sb.append(", ").append(userid);
        sb.append(", ").append(qsid);
        sb.append(", ").append(duplicate);
        sb.append(", ").append(originalSlug);
        sb.append(", ").append(reason);
        sb.append(", ").append(status);
        sb.append(", ").append(created);
        sb.append(", ").append(updated);

        sb.append(")");
        return sb.toString();
    }
}
