/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FosUser implements Serializable {

    private static final long serialVersionUID = 849107941;

    private Integer   id;
    private String    username;
    private String    usernameCanonical;
    private String    email;
    private String    emailCanonical;
    private Byte      enabled;
    private String    salt;
    private String    password;
    private Timestamp lastLogin;
    private String    confirmationToken;
    private Timestamp passwordRequestedAt;
    private String    roles;
    private Integer   userid;
    private Integer   ownerId;
    private Byte      isOwner;
    private String    localize;
    private String    slug;
    private String    status;
    private String    cropic;
    private String    logoUrl;

    public FosUser() {}

    public FosUser(FosUser value) {
        this.id = value.id;
        this.username = value.username;
        this.usernameCanonical = value.usernameCanonical;
        this.email = value.email;
        this.emailCanonical = value.emailCanonical;
        this.enabled = value.enabled;
        this.salt = value.salt;
        this.password = value.password;
        this.lastLogin = value.lastLogin;
        this.confirmationToken = value.confirmationToken;
        this.passwordRequestedAt = value.passwordRequestedAt;
        this.roles = value.roles;
        this.userid = value.userid;
        this.ownerId = value.ownerId;
        this.isOwner = value.isOwner;
        this.localize = value.localize;
        this.slug = value.slug;
        this.status = value.status;
        this.cropic = value.cropic;
        this.logoUrl = value.logoUrl;
    }

    public FosUser(
        Integer   id,
        String    username,
        String    usernameCanonical,
        String    email,
        String    emailCanonical,
        Byte      enabled,
        String    salt,
        String    password,
        Timestamp lastLogin,
        String    confirmationToken,
        Timestamp passwordRequestedAt,
        String    roles,
        Integer   userid,
        Integer   ownerId,
        Byte      isOwner,
        String    localize,
        String    slug,
        String    status,
        String    cropic,
        String    logoUrl
    ) {
        this.id = id;
        this.username = username;
        this.usernameCanonical = usernameCanonical;
        this.email = email;
        this.emailCanonical = emailCanonical;
        this.enabled = enabled;
        this.salt = salt;
        this.password = password;
        this.lastLogin = lastLogin;
        this.confirmationToken = confirmationToken;
        this.passwordRequestedAt = passwordRequestedAt;
        this.roles = roles;
        this.userid = userid;
        this.ownerId = ownerId;
        this.isOwner = isOwner;
        this.localize = localize;
        this.slug = slug;
        this.status = status;
        this.cropic = cropic;
        this.logoUrl = logoUrl;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUsernameCanonical() {
        return this.usernameCanonical;
    }

    public void setUsernameCanonical(String usernameCanonical) {
        this.usernameCanonical = usernameCanonical;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmailCanonical() {
        return this.emailCanonical;
    }

    public void setEmailCanonical(String emailCanonical) {
        this.emailCanonical = emailCanonical;
    }

    public Byte getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Byte enabled) {
        this.enabled = enabled;
    }

    public String getSalt() {
        return this.salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Timestamp getLastLogin() {
        return this.lastLogin;
    }

    public void setLastLogin(Timestamp lastLogin) {
        this.lastLogin = lastLogin;
    }

    public String getConfirmationToken() {
        return this.confirmationToken;
    }

    public void setConfirmationToken(String confirmationToken) {
        this.confirmationToken = confirmationToken;
    }

    public Timestamp getPasswordRequestedAt() {
        return this.passwordRequestedAt;
    }

    public void setPasswordRequestedAt(Timestamp passwordRequestedAt) {
        this.passwordRequestedAt = passwordRequestedAt;
    }

    public String getRoles() {
        return this.roles;
    }

    public void setRoles(String roles) {
        this.roles = roles;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public Integer getOwnerId() {
        return this.ownerId;
    }

    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    public Byte getIsOwner() {
        return this.isOwner;
    }

    public void setIsOwner(Byte isOwner) {
        this.isOwner = isOwner;
    }

    public String getLocalize() {
        return this.localize;
    }

    public void setLocalize(String localize) {
        this.localize = localize;
    }

    public String getSlug() {
        return this.slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCropic() {
        return this.cropic;
    }

    public void setCropic(String cropic) {
        this.cropic = cropic;
    }

    public String getLogoUrl() {
        return this.logoUrl;
    }

    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FosUser (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(usernameCanonical);
        sb.append(", ").append(email);
        sb.append(", ").append(emailCanonical);
        sb.append(", ").append(enabled);
        sb.append(", ").append(salt);
        sb.append(", ").append(password);
        sb.append(", ").append(lastLogin);
        sb.append(", ").append(confirmationToken);
        sb.append(", ").append(passwordRequestedAt);
        sb.append(", ").append(roles);
        sb.append(", ").append(userid);
        sb.append(", ").append(ownerId);
        sb.append(", ").append(isOwner);
        sb.append(", ").append(localize);
        sb.append(", ").append(slug);
        sb.append(", ").append(status);
        sb.append(", ").append(cropic);
        sb.append(", ").append(logoUrl);

        sb.append(")");
        return sb.toString();
    }
}
