/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Logger implements Serializable {

    private static final long serialVersionUID = -759800789;

    private Integer   id;
    private Integer   action;
    private Integer   userid;
    private Integer   answid;
    private Integer   qsid;
    private Integer   comid;
    private Integer   userSuspId;
    private Integer   permitid;
    private Integer   topicid;
    private String    status;
    private Timestamp created;
    private Timestamp updated;

    public Logger() {}

    public Logger(Logger value) {
        this.id = value.id;
        this.action = value.action;
        this.userid = value.userid;
        this.answid = value.answid;
        this.qsid = value.qsid;
        this.comid = value.comid;
        this.userSuspId = value.userSuspId;
        this.permitid = value.permitid;
        this.topicid = value.topicid;
        this.status = value.status;
        this.created = value.created;
        this.updated = value.updated;
    }

    public Logger(
        Integer   id,
        Integer   action,
        Integer   userid,
        Integer   answid,
        Integer   qsid,
        Integer   comid,
        Integer   userSuspId,
        Integer   permitid,
        Integer   topicid,
        String    status,
        Timestamp created,
        Timestamp updated
    ) {
        this.id = id;
        this.action = action;
        this.userid = userid;
        this.answid = answid;
        this.qsid = qsid;
        this.comid = comid;
        this.userSuspId = userSuspId;
        this.permitid = permitid;
        this.topicid = topicid;
        this.status = status;
        this.created = created;
        this.updated = updated;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getAction() {
        return this.action;
    }

    public void setAction(Integer action) {
        this.action = action;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public Integer getAnswid() {
        return this.answid;
    }

    public void setAnswid(Integer answid) {
        this.answid = answid;
    }

    public Integer getQsid() {
        return this.qsid;
    }

    public void setQsid(Integer qsid) {
        this.qsid = qsid;
    }

    public Integer getComid() {
        return this.comid;
    }

    public void setComid(Integer comid) {
        this.comid = comid;
    }

    public Integer getUserSuspId() {
        return this.userSuspId;
    }

    public void setUserSuspId(Integer userSuspId) {
        this.userSuspId = userSuspId;
    }

    public Integer getPermitid() {
        return this.permitid;
    }

    public void setPermitid(Integer permitid) {
        this.permitid = permitid;
    }

    public Integer getTopicid() {
        return this.topicid;
    }

    public void setTopicid(Integer topicid) {
        this.topicid = topicid;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Timestamp getUpdated() {
        return this.updated;
    }

    public void setUpdated(Timestamp updated) {
        this.updated = updated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Logger (");

        sb.append(id);
        sb.append(", ").append(action);
        sb.append(", ").append(userid);
        sb.append(", ").append(answid);
        sb.append(", ").append(qsid);
        sb.append(", ").append(comid);
        sb.append(", ").append(userSuspId);
        sb.append(", ").append(permitid);
        sb.append(", ").append(topicid);
        sb.append(", ").append(status);
        sb.append(", ").append(created);
        sb.append(", ").append(updated);

        sb.append(")");
        return sb.toString();
    }
}
