/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Messages implements Serializable {

    private static final long serialVersionUID = 1460078151;

    private Integer   id;
    private Integer   userFrom;
    private Integer   userTo;
    private String    message;
    private String    title;
    private String    status;
    private Byte      isNew;
    private Timestamp created;
    private Timestamp updated;

    public Messages() {}

    public Messages(Messages value) {
        this.id = value.id;
        this.userFrom = value.userFrom;
        this.userTo = value.userTo;
        this.message = value.message;
        this.title = value.title;
        this.status = value.status;
        this.isNew = value.isNew;
        this.created = value.created;
        this.updated = value.updated;
    }

    public Messages(
        Integer   id,
        Integer   userFrom,
        Integer   userTo,
        String    message,
        String    title,
        String    status,
        Byte      isNew,
        Timestamp created,
        Timestamp updated
    ) {
        this.id = id;
        this.userFrom = userFrom;
        this.userTo = userTo;
        this.message = message;
        this.title = title;
        this.status = status;
        this.isNew = isNew;
        this.created = created;
        this.updated = updated;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserFrom() {
        return this.userFrom;
    }

    public void setUserFrom(Integer userFrom) {
        this.userFrom = userFrom;
    }

    public Integer getUserTo() {
        return this.userTo;
    }

    public void setUserTo(Integer userTo) {
        this.userTo = userTo;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Byte getIsNew() {
        return this.isNew;
    }

    public void setIsNew(Byte isNew) {
        this.isNew = isNew;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Timestamp getUpdated() {
        return this.updated;
    }

    public void setUpdated(Timestamp updated) {
        this.updated = updated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Messages (");

        sb.append(id);
        sb.append(", ").append(userFrom);
        sb.append(", ").append(userTo);
        sb.append(", ").append(message);
        sb.append(", ").append(title);
        sb.append(", ").append(status);
        sb.append(", ").append(isNew);
        sb.append(", ").append(created);
        sb.append(", ").append(updated);

        sb.append(")");
        return sb.toString();
    }
}
