/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Permissions implements Serializable {

    private static final long serialVersionUID = -107234780;

    private Integer id;
    private Integer roleid;
    private Integer routeid;
    private Byte    permit;

    public Permissions() {}

    public Permissions(Permissions value) {
        this.id = value.id;
        this.roleid = value.roleid;
        this.routeid = value.routeid;
        this.permit = value.permit;
    }

    public Permissions(
        Integer id,
        Integer roleid,
        Integer routeid,
        Byte    permit
    ) {
        this.id = id;
        this.roleid = roleid;
        this.routeid = routeid;
        this.permit = permit;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getRoleid() {
        return this.roleid;
    }

    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    public Integer getRouteid() {
        return this.routeid;
    }

    public void setRouteid(Integer routeid) {
        this.routeid = routeid;
    }

    public Byte getPermit() {
        return this.permit;
    }

    public void setPermit(Byte permit) {
        this.permit = permit;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Permissions (");

        sb.append(id);
        sb.append(", ").append(roleid);
        sb.append(", ").append(routeid);
        sb.append(", ").append(permit);

        sb.append(")");
        return sb.toString();
    }
}
