/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QsToTopic implements Serializable {

    private static final long serialVersionUID = 1607002596;

    private Integer id;
    private Integer tpid;
    private Integer qsid;

    public QsToTopic() {}

    public QsToTopic(QsToTopic value) {
        this.id = value.id;
        this.tpid = value.tpid;
        this.qsid = value.qsid;
    }

    public QsToTopic(
        Integer id,
        Integer tpid,
        Integer qsid
    ) {
        this.id = id;
        this.tpid = tpid;
        this.qsid = qsid;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getTpid() {
        return this.tpid;
    }

    public void setTpid(Integer tpid) {
        this.tpid = tpid;
    }

    public Integer getQsid() {
        return this.qsid;
    }

    public void setQsid(Integer qsid) {
        this.qsid = qsid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QsToTopic (");

        sb.append(id);
        sb.append(", ").append(tpid);
        sb.append(", ").append(qsid);

        sb.append(")");
        return sb.toString();
    }
}
