/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routes implements Serializable {

    private static final long serialVersionUID = -888336565;

    private Integer id;
    private String  route;
    private String  title;

    public Routes() {}

    public Routes(Routes value) {
        this.id = value.id;
        this.route = value.route;
        this.title = value.title;
    }

    public Routes(
        Integer id,
        String  route,
        String  title
    ) {
        this.id = id;
        this.route = route;
        this.title = title;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getRoute() {
        return this.route;
    }

    public void setRoute(String route) {
        this.route = route;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Routes (");

        sb.append(id);
        sb.append(", ").append(route);
        sb.append(", ").append(title);

        sb.append(")");
        return sb.toString();
    }
}
