/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeoRedirect implements Serializable {

    private static final long serialVersionUID = 1694527939;

    private Integer   id;
    private Integer   qsid;
    private Integer   tpid;
    private String    newAlias;
    private String    oldAlias;
    private String    newSegment;
    private String    oldSegment;
    private String    type;
    private Byte      status;
    private Timestamp created;
    private Timestamp updated;

    public SeoRedirect() {}

    public SeoRedirect(SeoRedirect value) {
        this.id = value.id;
        this.qsid = value.qsid;
        this.tpid = value.tpid;
        this.newAlias = value.newAlias;
        this.oldAlias = value.oldAlias;
        this.newSegment = value.newSegment;
        this.oldSegment = value.oldSegment;
        this.type = value.type;
        this.status = value.status;
        this.created = value.created;
        this.updated = value.updated;
    }

    public SeoRedirect(
        Integer   id,
        Integer   qsid,
        Integer   tpid,
        String    newAlias,
        String    oldAlias,
        String    newSegment,
        String    oldSegment,
        String    type,
        Byte      status,
        Timestamp created,
        Timestamp updated
    ) {
        this.id = id;
        this.qsid = qsid;
        this.tpid = tpid;
        this.newAlias = newAlias;
        this.oldAlias = oldAlias;
        this.newSegment = newSegment;
        this.oldSegment = oldSegment;
        this.type = type;
        this.status = status;
        this.created = created;
        this.updated = updated;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getQsid() {
        return this.qsid;
    }

    public void setQsid(Integer qsid) {
        this.qsid = qsid;
    }

    public Integer getTpid() {
        return this.tpid;
    }

    public void setTpid(Integer tpid) {
        this.tpid = tpid;
    }

    public String getNewAlias() {
        return this.newAlias;
    }

    public void setNewAlias(String newAlias) {
        this.newAlias = newAlias;
    }

    public String getOldAlias() {
        return this.oldAlias;
    }

    public void setOldAlias(String oldAlias) {
        this.oldAlias = oldAlias;
    }

    public String getNewSegment() {
        return this.newSegment;
    }

    public void setNewSegment(String newSegment) {
        this.newSegment = newSegment;
    }

    public String getOldSegment() {
        return this.oldSegment;
    }

    public void setOldSegment(String oldSegment) {
        this.oldSegment = oldSegment;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Timestamp getUpdated() {
        return this.updated;
    }

    public void setUpdated(Timestamp updated) {
        this.updated = updated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SeoRedirect (");

        sb.append(id);
        sb.append(", ").append(qsid);
        sb.append(", ").append(tpid);
        sb.append(", ").append(newAlias);
        sb.append(", ").append(oldAlias);
        sb.append(", ").append(newSegment);
        sb.append(", ").append(oldSegment);
        sb.append(", ").append(type);
        sb.append(", ").append(status);
        sb.append(", ").append(created);
        sb.append(", ").append(updated);

        sb.append(")");
        return sb.toString();
    }
}
