/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Topics implements Serializable {

    private static final long serialVersionUID = 1739770997;

    private Integer   id;
    private String    topic;
    private String    content;
    private String    slug;
    private String    cropic;
    private String    segment;
    private String    status;
    private Timestamp created;
    private Timestamp updated;

    public Topics() {}

    public Topics(Topics value) {
        this.id = value.id;
        this.topic = value.topic;
        this.content = value.content;
        this.slug = value.slug;
        this.cropic = value.cropic;
        this.segment = value.segment;
        this.status = value.status;
        this.created = value.created;
        this.updated = value.updated;
    }

    public Topics(
        Integer   id,
        String    topic,
        String    content,
        String    slug,
        String    cropic,
        String    segment,
        String    status,
        Timestamp created,
        Timestamp updated
    ) {
        this.id = id;
        this.topic = topic;
        this.content = content;
        this.slug = slug;
        this.cropic = cropic;
        this.segment = segment;
        this.status = status;
        this.created = created;
        this.updated = updated;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTopic() {
        return this.topic;
    }

    public void setTopic(String topic) {
        this.topic = topic;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getSlug() {
        return this.slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getCropic() {
        return this.cropic;
    }

    public void setCropic(String cropic) {
        this.cropic = cropic;
    }

    public String getSegment() {
        return this.segment;
    }

    public void setSegment(String segment) {
        this.segment = segment;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Timestamp getUpdated() {
        return this.updated;
    }

    public void setUpdated(Timestamp updated) {
        this.updated = updated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Topics (");

        sb.append(id);
        sb.append(", ").append(topic);
        sb.append(", ").append(content);
        sb.append(", ").append(slug);
        sb.append(", ").append(cropic);
        sb.append(", ").append(segment);
        sb.append(", ").append(status);
        sb.append(", ").append(created);
        sb.append(", ").append(updated);

        sb.append(")");
        return sb.toString();
    }
}
