/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserToVotes implements Serializable {

    private static final long serialVersionUID = -1909365122;

    private Integer id;
    private Integer usid;
    private Integer qsid;
    private Integer answid;
    private Integer comid;
    private String  type;

    public UserToVotes() {}

    public UserToVotes(UserToVotes value) {
        this.id = value.id;
        this.usid = value.usid;
        this.qsid = value.qsid;
        this.answid = value.answid;
        this.comid = value.comid;
        this.type = value.type;
    }

    public UserToVotes(
        Integer id,
        Integer usid,
        Integer qsid,
        Integer answid,
        Integer comid,
        String  type
    ) {
        this.id = id;
        this.usid = usid;
        this.qsid = qsid;
        this.answid = answid;
        this.comid = comid;
        this.type = type;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUsid() {
        return this.usid;
    }

    public void setUsid(Integer usid) {
        this.usid = usid;
    }

    public Integer getQsid() {
        return this.qsid;
    }

    public void setQsid(Integer qsid) {
        this.qsid = qsid;
    }

    public Integer getAnswid() {
        return this.answid;
    }

    public void setAnswid(Integer answid) {
        this.answid = answid;
    }

    public Integer getComid() {
        return this.comid;
    }

    public void setComid(Integer comid) {
        this.comid = comid;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserToVotes (");

        sb.append(id);
        sb.append(", ").append(usid);
        sb.append(", ").append(qsid);
        sb.append(", ").append(answid);
        sb.append(", ").append(comid);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
