/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserToFavorites implements Serializable {

    private static final long serialVersionUID = -592442354;

    private Integer id;
    private Integer usid;
    private Integer qsid;
    private Integer answid;
    private Integer usidfav;
    private Integer topid;

    public UserToFavorites() {}

    public UserToFavorites(UserToFavorites value) {
        this.id = value.id;
        this.usid = value.usid;
        this.qsid = value.qsid;
        this.answid = value.answid;
        this.usidfav = value.usidfav;
        this.topid = value.topid;
    }

    public UserToFavorites(
        Integer id,
        Integer usid,
        Integer qsid,
        Integer answid,
        Integer usidfav,
        Integer topid
    ) {
        this.id = id;
        this.usid = usid;
        this.qsid = qsid;
        this.answid = answid;
        this.usidfav = usidfav;
        this.topid = topid;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUsid() {
        return this.usid;
    }

    public void setUsid(Integer usid) {
        this.usid = usid;
    }

    public Integer getQsid() {
        return this.qsid;
    }

    public void setQsid(Integer qsid) {
        this.qsid = qsid;
    }

    public Integer getAnswid() {
        return this.answid;
    }

    public void setAnswid(Integer answid) {
        this.answid = answid;
    }

    public Integer getUsidfav() {
        return this.usidfav;
    }

    public void setUsidfav(Integer usidfav) {
        this.usidfav = usidfav;
    }

    public Integer getTopid() {
        return this.topid;
    }

    public void setTopid(Integer topid) {
        this.topid = topid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserToFavorites (");

        sb.append(id);
        sb.append(", ").append(usid);
        sb.append(", ").append(qsid);
        sb.append(", ").append(answid);
        sb.append(", ").append(usidfav);
        sb.append(", ").append(topid);

        sb.append(")");
        return sb.toString();
    }
}
