/*
 * This file is generated by jOOQ.
*/
package lorgNew;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import lorgNew.tables.Answers;
import lorgNew.tables.Closed;
import lorgNew.tables.Comments;
import lorgNew.tables.FosUser;
import lorgNew.tables.Logger;
import lorgNew.tables.LoggerActions;
import lorgNew.tables.Messages;
import lorgNew.tables.Permissions;
import lorgNew.tables.QsToTopic;
import lorgNew.tables.Questions;
import lorgNew.tables.Roles;
import lorgNew.tables.Routes;
import lorgNew.tables.SeoProfile;
import lorgNew.tables.SeoRedirect;
import lorgNew.tables.SeoStationary;
import lorgNew.tables.Topics;
import lorgNew.tables.UserProfile;
import lorgNew.tables.UserToFavorites;
import lorgNew.tables.UserToVotes;
import lorgNew.tables.Votes;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lorgnew extends SchemaImpl {

    private static final long serialVersionUID = 979762161;

    /**
     * The reference instance of <code>lorgNew</code>
     */
    public static final Lorgnew LORGNEW = new Lorgnew();

    /**
     * The table <code>lorgNew.answers</code>.
     */
    public final Answers ANSWERS = lorgNew.tables.Answers.ANSWERS;

    /**
     * The table <code>lorgNew.closed</code>.
     */
    public final Closed CLOSED = lorgNew.tables.Closed.CLOSED;

    /**
     * The table <code>lorgNew.comments</code>.
     */
    public final Comments COMMENTS = lorgNew.tables.Comments.COMMENTS;

    /**
     * The table <code>lorgNew.fos_user</code>.
     */
    public final FosUser FOS_USER = lorgNew.tables.FosUser.FOS_USER;

    /**
     * The table <code>lorgNew.logger</code>.
     */
    public final Logger LOGGER = lorgNew.tables.Logger.LOGGER;

    /**
     * The table <code>lorgNew.logger_actions</code>.
     */
    public final LoggerActions LOGGER_ACTIONS = lorgNew.tables.LoggerActions.LOGGER_ACTIONS;

    /**
     * The table <code>lorgNew.messages</code>.
     */
    public final Messages MESSAGES = lorgNew.tables.Messages.MESSAGES;

    /**
     * The table <code>lorgNew.permissions</code>.
     */
    public final Permissions PERMISSIONS = lorgNew.tables.Permissions.PERMISSIONS;

    /**
     * The table <code>lorgNew.qs_to_topic</code>.
     */
    public final QsToTopic QS_TO_TOPIC = lorgNew.tables.QsToTopic.QS_TO_TOPIC;

    /**
     * The table <code>lorgNew.questions</code>.
     */
    public final Questions QUESTIONS = lorgNew.tables.Questions.QUESTIONS;

    /**
     * The table <code>lorgNew.roles</code>.
     */
    public final Roles ROLES = lorgNew.tables.Roles.ROLES;

    /**
     * The table <code>lorgNew.routes</code>.
     */
    public final Routes ROUTES = lorgNew.tables.Routes.ROUTES;

    /**
     * The table <code>lorgNew.seo_profile</code>.
     */
    public final SeoProfile SEO_PROFILE = lorgNew.tables.SeoProfile.SEO_PROFILE;

    /**
     * The table <code>lorgNew.seo_redirect</code>.
     */
    public final SeoRedirect SEO_REDIRECT = lorgNew.tables.SeoRedirect.SEO_REDIRECT;

    /**
     * The table <code>lorgNew.seo_stationary</code>.
     */
    public final SeoStationary SEO_STATIONARY = lorgNew.tables.SeoStationary.SEO_STATIONARY;

    /**
     * The table <code>lorgNew.topics</code>.
     */
    public final Topics TOPICS = lorgNew.tables.Topics.TOPICS;

    /**
     * The table <code>lorgNew.user_profile</code>.
     */
    public final UserProfile USER_PROFILE = lorgNew.tables.UserProfile.USER_PROFILE;

    /**
     * The table <code>lorgNew.user_to_favorites</code>.
     */
    public final UserToFavorites USER_TO_FAVORITES = lorgNew.tables.UserToFavorites.USER_TO_FAVORITES;

    /**
     * The table <code>lorgNew.user_to_votes</code>.
     */
    public final UserToVotes USER_TO_VOTES = lorgNew.tables.UserToVotes.USER_TO_VOTES;

    /**
     * The table <code>lorgNew.votes</code>.
     */
    public final Votes VOTES = lorgNew.tables.Votes.VOTES;

    /**
     * No further instances allowed
     */
    private Lorgnew() {
        super("lorgNew", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Answers.ANSWERS,
            Closed.CLOSED,
            Comments.COMMENTS,
            FosUser.FOS_USER,
            Logger.LOGGER,
            LoggerActions.LOGGER_ACTIONS,
            Messages.MESSAGES,
            Permissions.PERMISSIONS,
            QsToTopic.QS_TO_TOPIC,
            Questions.QUESTIONS,
            Roles.ROLES,
            Routes.ROUTES,
            SeoProfile.SEO_PROFILE,
            SeoRedirect.SEO_REDIRECT,
            SeoStationary.SEO_STATIONARY,
            Topics.TOPICS,
            UserProfile.USER_PROFILE,
            UserToFavorites.USER_TO_FAVORITES,
            UserToVotes.USER_TO_VOTES,
            Votes.VOTES);
    }
}
