/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import lorgNew.tables.Answers;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnswersRecord extends UpdatableRecordImpl<AnswersRecord> implements Record9<Integer, Integer, Integer, String, String, String, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = -301278771;

    /**
     * Setter for <code>lorgNew.answers.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lorgNew.answers.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lorgNew.answers.qsid</code>.
     */
    public void setQsid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lorgNew.answers.qsid</code>.
     */
    public Integer getQsid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lorgNew.answers.userid</code>.
     */
    public void setUserid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lorgNew.answers.userid</code>.
     */
    public Integer getUserid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>lorgNew.answers.content</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lorgNew.answers.content</code>.
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lorgNew.answers.slug</code>.
     */
    public void setSlug(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>lorgNew.answers.slug</code>.
     */
    public String getSlug() {
        return (String) get(4);
    }

    /**
     * Setter for <code>lorgNew.answers.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>lorgNew.answers.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>lorgNew.answers.mailme</code>.
     */
    public void setMailme(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>lorgNew.answers.mailme</code>.
     */
    public Byte getMailme() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>lorgNew.answers.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>lorgNew.answers.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>lorgNew.answers.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>lorgNew.answers.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, String, String, String, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, String, String, String, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Answers.ANSWERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Answers.ANSWERS.QSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Answers.ANSWERS.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Answers.ANSWERS.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Answers.ANSWERS.SLUG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Answers.ANSWERS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return Answers.ANSWERS.MAILME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Answers.ANSWERS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Answers.ANSWERS.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getQsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getMailme();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getQsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getMailme();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnswersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnswersRecord value2(Integer value) {
        setQsid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnswersRecord value3(Integer value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnswersRecord value4(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnswersRecord value5(String value) {
        setSlug(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnswersRecord value6(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnswersRecord value7(Byte value) {
        setMailme(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnswersRecord value8(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnswersRecord value9(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnswersRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, Byte value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AnswersRecord
     */
    public AnswersRecord() {
        super(Answers.ANSWERS);
    }

    /**
     * Create a detached, initialised AnswersRecord
     */
    public AnswersRecord(Integer id, Integer qsid, Integer userid, String content, String slug, String status, Byte mailme, Timestamp created, Timestamp updated) {
        super(Answers.ANSWERS);

        set(0, id);
        set(1, qsid);
        set(2, userid);
        set(3, content);
        set(4, slug);
        set(5, status);
        set(6, mailme);
        set(7, created);
        set(8, updated);
    }
}
