/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import lorgNew.tables.Closed;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClosedRecord extends UpdatableRecordImpl<ClosedRecord> implements Record9<Integer, Integer, Integer, Byte, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -2036740413;

    /**
     * Setter for <code>lorgNew.closed.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lorgNew.closed.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lorgNew.closed.userid</code>.
     */
    public void setUserid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lorgNew.closed.userid</code>.
     */
    public Integer getUserid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lorgNew.closed.qsid</code>.
     */
    public void setQsid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lorgNew.closed.qsid</code>.
     */
    public Integer getQsid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>lorgNew.closed.duplicate</code>.
     */
    public void setDuplicate(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>lorgNew.closed.duplicate</code>.
     */
    public Byte getDuplicate() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>lorgNew.closed.original_slug</code>.
     */
    public void setOriginalSlug(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>lorgNew.closed.original_slug</code>.
     */
    public String getOriginalSlug() {
        return (String) get(4);
    }

    /**
     * Setter for <code>lorgNew.closed.reason</code>.
     */
    public void setReason(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>lorgNew.closed.reason</code>.
     */
    public String getReason() {
        return (String) get(5);
    }

    /**
     * Setter for <code>lorgNew.closed.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>lorgNew.closed.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>lorgNew.closed.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>lorgNew.closed.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>lorgNew.closed.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>lorgNew.closed.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Byte, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Byte, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Closed.CLOSED.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Closed.CLOSED.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Closed.CLOSED.QSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return Closed.CLOSED.DUPLICATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Closed.CLOSED.ORIGINAL_SLUG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Closed.CLOSED.REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Closed.CLOSED.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Closed.CLOSED.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Closed.CLOSED.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getQsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getDuplicate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getOriginalSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getQsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getDuplicate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOriginalSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClosedRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClosedRecord value2(Integer value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClosedRecord value3(Integer value) {
        setQsid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClosedRecord value4(Byte value) {
        setDuplicate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClosedRecord value5(String value) {
        setOriginalSlug(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClosedRecord value6(String value) {
        setReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClosedRecord value7(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClosedRecord value8(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClosedRecord value9(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClosedRecord values(Integer value1, Integer value2, Integer value3, Byte value4, String value5, String value6, String value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClosedRecord
     */
    public ClosedRecord() {
        super(Closed.CLOSED);
    }

    /**
     * Create a detached, initialised ClosedRecord
     */
    public ClosedRecord(Integer id, Integer userid, Integer qsid, Byte duplicate, String originalSlug, String reason, String status, Timestamp created, Timestamp updated) {
        super(Closed.CLOSED);

        set(0, id);
        set(1, userid);
        set(2, qsid);
        set(3, duplicate);
        set(4, originalSlug);
        set(5, reason);
        set(6, status);
        set(7, created);
        set(8, updated);
    }
}
