/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import lorgNew.tables.Comments;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentsRecord extends UpdatableRecordImpl<CommentsRecord> implements Record10<Integer, Integer, Integer, Integer, Integer, String, Integer, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1348331602;

    /**
     * Setter for <code>lorgNew.comments.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lorgNew.comments.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lorgNew.comments.answid</code>.
     */
    public void setAnswid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lorgNew.comments.answid</code>.
     */
    public Integer getAnswid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lorgNew.comments.qsid</code>.
     */
    public void setQsid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lorgNew.comments.qsid</code>.
     */
    public Integer getQsid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>lorgNew.comments.comid</code>.
     */
    public void setComid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>lorgNew.comments.comid</code>.
     */
    public Integer getComid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>lorgNew.comments.userid</code>.
     */
    public void setUserid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>lorgNew.comments.userid</code>.
     */
    public Integer getUserid() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>lorgNew.comments.content</code>.
     */
    public void setContent(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>lorgNew.comments.content</code>.
     */
    public String getContent() {
        return (String) get(5);
    }

    /**
     * Setter for <code>lorgNew.comments.depth</code>.
     */
    public void setDepth(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>lorgNew.comments.depth</code>.
     */
    public Integer getDepth() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>lorgNew.comments.mailme</code>.
     */
    public void setMailme(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>lorgNew.comments.mailme</code>.
     */
    public Byte getMailme() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>lorgNew.comments.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>lorgNew.comments.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>lorgNew.comments.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>lorgNew.comments.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, Integer, Integer, String, Integer, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, Integer, Integer, String, Integer, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Comments.COMMENTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Comments.COMMENTS.ANSWID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Comments.COMMENTS.QSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Comments.COMMENTS.COMID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Comments.COMMENTS.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Comments.COMMENTS.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Comments.COMMENTS.DEPTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return Comments.COMMENTS.MAILME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Comments.COMMENTS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Comments.COMMENTS.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getAnswid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getQsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getComid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getDepth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component8() {
        return getMailme();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAnswid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getQsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getComid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getDepth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getMailme();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentsRecord value2(Integer value) {
        setAnswid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentsRecord value3(Integer value) {
        setQsid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentsRecord value4(Integer value) {
        setComid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentsRecord value5(Integer value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentsRecord value6(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentsRecord value7(Integer value) {
        setDepth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentsRecord value8(Byte value) {
        setMailme(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentsRecord value9(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentsRecord value10(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, String value6, Integer value7, Byte value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommentsRecord
     */
    public CommentsRecord() {
        super(Comments.COMMENTS);
    }

    /**
     * Create a detached, initialised CommentsRecord
     */
    public CommentsRecord(Integer id, Integer answid, Integer qsid, Integer comid, Integer userid, String content, Integer depth, Byte mailme, Timestamp created, Timestamp updated) {
        super(Comments.COMMENTS);

        set(0, id);
        set(1, answid);
        set(2, qsid);
        set(3, comid);
        set(4, userid);
        set(5, content);
        set(6, depth);
        set(7, mailme);
        set(8, created);
        set(9, updated);
    }
}
