/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import lorgNew.tables.Logger;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoggerRecord extends UpdatableRecordImpl<LoggerRecord> implements Record12<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1902521142;

    /**
     * Setter for <code>lorgNew.logger.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lorgNew.logger.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lorgNew.logger.action</code>.
     */
    public void setAction(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lorgNew.logger.action</code>.
     */
    public Integer getAction() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lorgNew.logger.userid</code>.
     */
    public void setUserid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lorgNew.logger.userid</code>.
     */
    public Integer getUserid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>lorgNew.logger.answid</code>.
     */
    public void setAnswid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>lorgNew.logger.answid</code>.
     */
    public Integer getAnswid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>lorgNew.logger.qsid</code>.
     */
    public void setQsid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>lorgNew.logger.qsid</code>.
     */
    public Integer getQsid() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>lorgNew.logger.comid</code>.
     */
    public void setComid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>lorgNew.logger.comid</code>.
     */
    public Integer getComid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>lorgNew.logger.user_susp_id</code>.
     */
    public void setUserSuspId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>lorgNew.logger.user_susp_id</code>.
     */
    public Integer getUserSuspId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>lorgNew.logger.permitid</code>.
     */
    public void setPermitid(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>lorgNew.logger.permitid</code>.
     */
    public Integer getPermitid() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>lorgNew.logger.topicid</code>.
     */
    public void setTopicid(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>lorgNew.logger.topicid</code>.
     */
    public Integer getTopicid() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>lorgNew.logger.status</code>.
     */
    public void setStatus(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>lorgNew.logger.status</code>.
     */
    public String getStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>lorgNew.logger.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>lorgNew.logger.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>lorgNew.logger.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>lorgNew.logger.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, Timestamp, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Logger.LOGGER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Logger.LOGGER.ACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Logger.LOGGER.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Logger.LOGGER.ANSWID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Logger.LOGGER.QSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Logger.LOGGER.COMID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Logger.LOGGER.USER_SUSP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Logger.LOGGER.PERMITID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Logger.LOGGER.TOPICID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Logger.LOGGER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return Logger.LOGGER.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return Logger.LOGGER.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getAnswid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getQsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getComid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getUserSuspId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getPermitid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getTopicid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAnswid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getQsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getComid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getUserSuspId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getPermitid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getTopicid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoggerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoggerRecord value2(Integer value) {
        setAction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoggerRecord value3(Integer value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoggerRecord value4(Integer value) {
        setAnswid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoggerRecord value5(Integer value) {
        setQsid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoggerRecord value6(Integer value) {
        setComid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoggerRecord value7(Integer value) {
        setUserSuspId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoggerRecord value8(Integer value) {
        setPermitid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoggerRecord value9(Integer value) {
        setTopicid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoggerRecord value10(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoggerRecord value11(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoggerRecord value12(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoggerRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, String value10, Timestamp value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoggerRecord
     */
    public LoggerRecord() {
        super(Logger.LOGGER);
    }

    /**
     * Create a detached, initialised LoggerRecord
     */
    public LoggerRecord(Integer id, Integer action, Integer userid, Integer answid, Integer qsid, Integer comid, Integer userSuspId, Integer permitid, Integer topicid, String status, Timestamp created, Timestamp updated) {
        super(Logger.LOGGER);

        set(0, id);
        set(1, action);
        set(2, userid);
        set(3, answid);
        set(4, qsid);
        set(5, comid);
        set(6, userSuspId);
        set(7, permitid);
        set(8, topicid);
        set(9, status);
        set(10, created);
        set(11, updated);
    }
}
