/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import lorgNew.tables.Questions;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuestionsRecord extends UpdatableRecordImpl<QuestionsRecord> implements Record11<Integer, Integer, String, String, Integer, String, String, Byte, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -652934584;

    /**
     * Setter for <code>lorgNew.questions.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lorgNew.questions.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lorgNew.questions.userid</code>.
     */
    public void setUserid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lorgNew.questions.userid</code>.
     */
    public Integer getUserid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lorgNew.questions.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lorgNew.questions.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lorgNew.questions.content</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lorgNew.questions.content</code>.
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lorgNew.questions.views</code>.
     */
    public void setViews(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>lorgNew.questions.views</code>.
     */
    public Integer getViews() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>lorgNew.questions.slug</code>.
     */
    public void setSlug(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>lorgNew.questions.slug</code>.
     */
    public String getSlug() {
        return (String) get(5);
    }

    /**
     * Setter for <code>lorgNew.questions.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>lorgNew.questions.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>lorgNew.questions.mailme</code>.
     */
    public void setMailme(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>lorgNew.questions.mailme</code>.
     */
    public Byte getMailme() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>lorgNew.questions.segment</code>.
     */
    public void setSegment(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>lorgNew.questions.segment</code>.
     */
    public String getSegment() {
        return (String) get(8);
    }

    /**
     * Setter for <code>lorgNew.questions.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>lorgNew.questions.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>lorgNew.questions.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>lorgNew.questions.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, String, String, Integer, String, String, Byte, String, Timestamp, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, String, String, Integer, String, String, Byte, String, Timestamp, Timestamp> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Questions.QUESTIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Questions.QUESTIONS.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Questions.QUESTIONS.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Questions.QUESTIONS.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Questions.QUESTIONS.VIEWS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Questions.QUESTIONS.SLUG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Questions.QUESTIONS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return Questions.QUESTIONS.MAILME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Questions.QUESTIONS.SEGMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Questions.QUESTIONS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return Questions.QUESTIONS.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getViews();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component8() {
        return getMailme();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getSegment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getViews();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getMailme();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getSegment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestionsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestionsRecord value2(Integer value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestionsRecord value3(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestionsRecord value4(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestionsRecord value5(Integer value) {
        setViews(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestionsRecord value6(String value) {
        setSlug(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestionsRecord value7(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestionsRecord value8(Byte value) {
        setMailme(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestionsRecord value9(String value) {
        setSegment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestionsRecord value10(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestionsRecord value11(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestionsRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5, String value6, String value7, Byte value8, String value9, Timestamp value10, Timestamp value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuestionsRecord
     */
    public QuestionsRecord() {
        super(Questions.QUESTIONS);
    }

    /**
     * Create a detached, initialised QuestionsRecord
     */
    public QuestionsRecord(Integer id, Integer userid, String title, String content, Integer views, String slug, String status, Byte mailme, String segment, Timestamp created, Timestamp updated) {
        super(Questions.QUESTIONS);

        set(0, id);
        set(1, userid);
        set(2, title);
        set(3, content);
        set(4, views);
        set(5, slug);
        set(6, status);
        set(7, mailme);
        set(8, segment);
        set(9, created);
        set(10, updated);
    }
}
