/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import lorgNew.tables.SeoRedirect;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeoRedirectRecord extends UpdatableRecordImpl<SeoRedirectRecord> implements Record11<Integer, Integer, Integer, String, String, String, String, String, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = 173424467;

    /**
     * Setter for <code>lorgNew.seo_redirect.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lorgNew.seo_redirect.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lorgNew.seo_redirect.qsid</code>.
     */
    public void setQsid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lorgNew.seo_redirect.qsid</code>.
     */
    public Integer getQsid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lorgNew.seo_redirect.tpid</code>.
     */
    public void setTpid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lorgNew.seo_redirect.tpid</code>.
     */
    public Integer getTpid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>lorgNew.seo_redirect.new_alias</code>.
     */
    public void setNewAlias(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lorgNew.seo_redirect.new_alias</code>.
     */
    public String getNewAlias() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lorgNew.seo_redirect.old_alias</code>.
     */
    public void setOldAlias(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>lorgNew.seo_redirect.old_alias</code>.
     */
    public String getOldAlias() {
        return (String) get(4);
    }

    /**
     * Setter for <code>lorgNew.seo_redirect.new_segment</code>.
     */
    public void setNewSegment(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>lorgNew.seo_redirect.new_segment</code>.
     */
    public String getNewSegment() {
        return (String) get(5);
    }

    /**
     * Setter for <code>lorgNew.seo_redirect.old_segment</code>.
     */
    public void setOldSegment(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>lorgNew.seo_redirect.old_segment</code>.
     */
    public String getOldSegment() {
        return (String) get(6);
    }

    /**
     * Setter for <code>lorgNew.seo_redirect.type</code>.
     */
    public void setType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>lorgNew.seo_redirect.type</code>.
     */
    public String getType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>lorgNew.seo_redirect.status</code>.
     */
    public void setStatus(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>lorgNew.seo_redirect.status</code>.
     */
    public Byte getStatus() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>lorgNew.seo_redirect.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>lorgNew.seo_redirect.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>lorgNew.seo_redirect.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>lorgNew.seo_redirect.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, Integer, String, String, String, String, String, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, Integer, String, String, String, String, String, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SeoRedirect.SEO_REDIRECT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SeoRedirect.SEO_REDIRECT.QSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return SeoRedirect.SEO_REDIRECT.TPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SeoRedirect.SEO_REDIRECT.NEW_ALIAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SeoRedirect.SEO_REDIRECT.OLD_ALIAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SeoRedirect.SEO_REDIRECT.NEW_SEGMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SeoRedirect.SEO_REDIRECT.OLD_SEGMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return SeoRedirect.SEO_REDIRECT.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return SeoRedirect.SEO_REDIRECT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return SeoRedirect.SEO_REDIRECT.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return SeoRedirect.SEO_REDIRECT.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getQsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getTpid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getNewAlias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getOldAlias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getNewSegment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getOldSegment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getQsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTpid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNewAlias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOldAlias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNewSegment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getOldSegment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoRedirectRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoRedirectRecord value2(Integer value) {
        setQsid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoRedirectRecord value3(Integer value) {
        setTpid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoRedirectRecord value4(String value) {
        setNewAlias(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoRedirectRecord value5(String value) {
        setOldAlias(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoRedirectRecord value6(String value) {
        setNewSegment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoRedirectRecord value7(String value) {
        setOldSegment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoRedirectRecord value8(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoRedirectRecord value9(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoRedirectRecord value10(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoRedirectRecord value11(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoRedirectRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, String value7, String value8, Byte value9, Timestamp value10, Timestamp value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SeoRedirectRecord
     */
    public SeoRedirectRecord() {
        super(SeoRedirect.SEO_REDIRECT);
    }

    /**
     * Create a detached, initialised SeoRedirectRecord
     */
    public SeoRedirectRecord(Integer id, Integer qsid, Integer tpid, String newAlias, String oldAlias, String newSegment, String oldSegment, String type, Byte status, Timestamp created, Timestamp updated) {
        super(SeoRedirect.SEO_REDIRECT);

        set(0, id);
        set(1, qsid);
        set(2, tpid);
        set(3, newAlias);
        set(4, oldAlias);
        set(5, newSegment);
        set(6, oldSegment);
        set(7, type);
        set(8, status);
        set(9, created);
        set(10, updated);
    }
}
