/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.records;


import javax.annotation.Generated;

import lorgNew.tables.SeoStationary;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeoStationaryRecord extends UpdatableRecordImpl<SeoStationaryRecord> implements Record10<Integer, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -1409167978;

    /**
     * Setter for <code>lorgNew.seo_stationary.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lorgNew.seo_stationary.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lorgNew.seo_stationary.page</code>.
     */
    public void setPage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lorgNew.seo_stationary.page</code>.
     */
    public String getPage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lorgNew.seo_stationary.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lorgNew.seo_stationary.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lorgNew.seo_stationary.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lorgNew.seo_stationary.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lorgNew.seo_stationary.segment</code>.
     */
    public void setSegment(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>lorgNew.seo_stationary.segment</code>.
     */
    public String getSegment() {
        return (String) get(4);
    }

    /**
     * Setter for <code>lorgNew.seo_stationary.hrefland_default_location</code>.
     */
    public void setHreflandDefaultLocation(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>lorgNew.seo_stationary.hrefland_default_location</code>.
     */
    public String getHreflandDefaultLocation() {
        return (String) get(5);
    }

    /**
     * Setter for <code>lorgNew.seo_stationary.hrefland_for_english</code>.
     */
    public void setHreflandForEnglish(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>lorgNew.seo_stationary.hrefland_for_english</code>.
     */
    public String getHreflandForEnglish() {
        return (String) get(6);
    }

    /**
     * Setter for <code>lorgNew.seo_stationary.hrefland_for_spanish</code>.
     */
    public void setHreflandForSpanish(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>lorgNew.seo_stationary.hrefland_for_spanish</code>.
     */
    public String getHreflandForSpanish() {
        return (String) get(7);
    }

    /**
     * Setter for <code>lorgNew.seo_stationary.hrefland_for_korean</code>.
     */
    public void setHreflandForKorean(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>lorgNew.seo_stationary.hrefland_for_korean</code>.
     */
    public String getHreflandForKorean() {
        return (String) get(8);
    }

    /**
     * Setter for <code>lorgNew.seo_stationary.hrefland_for_japanese</code>.
     */
    public void setHreflandForJapanese(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>lorgNew.seo_stationary.hrefland_for_japanese</code>.
     */
    public String getHreflandForJapanese() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SeoStationary.SEO_STATIONARY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SeoStationary.SEO_STATIONARY.PAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SeoStationary.SEO_STATIONARY.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SeoStationary.SEO_STATIONARY.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SeoStationary.SEO_STATIONARY.SEGMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SeoStationary.SEO_STATIONARY.HREFLAND_DEFAULT_LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SeoStationary.SEO_STATIONARY.HREFLAND_FOR_ENGLISH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return SeoStationary.SEO_STATIONARY.HREFLAND_FOR_SPANISH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return SeoStationary.SEO_STATIONARY.HREFLAND_FOR_KOREAN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return SeoStationary.SEO_STATIONARY.HREFLAND_FOR_JAPANESE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSegment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getHreflandDefaultLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getHreflandForEnglish();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getHreflandForSpanish();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getHreflandForKorean();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getHreflandForJapanese();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSegment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getHreflandDefaultLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getHreflandForEnglish();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getHreflandForSpanish();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getHreflandForKorean();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getHreflandForJapanese();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoStationaryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoStationaryRecord value2(String value) {
        setPage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoStationaryRecord value3(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoStationaryRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoStationaryRecord value5(String value) {
        setSegment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoStationaryRecord value6(String value) {
        setHreflandDefaultLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoStationaryRecord value7(String value) {
        setHreflandForEnglish(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoStationaryRecord value8(String value) {
        setHreflandForSpanish(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoStationaryRecord value9(String value) {
        setHreflandForKorean(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoStationaryRecord value10(String value) {
        setHreflandForJapanese(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeoStationaryRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SeoStationaryRecord
     */
    public SeoStationaryRecord() {
        super(SeoStationary.SEO_STATIONARY);
    }

    /**
     * Create a detached, initialised SeoStationaryRecord
     */
    public SeoStationaryRecord(Integer id, String page, String title, String description, String segment, String hreflandDefaultLocation, String hreflandForEnglish, String hreflandForSpanish, String hreflandForKorean, String hreflandForJapanese) {
        super(SeoStationary.SEO_STATIONARY);

        set(0, id);
        set(1, page);
        set(2, title);
        set(3, description);
        set(4, segment);
        set(5, hreflandDefaultLocation);
        set(6, hreflandForEnglish);
        set(7, hreflandForSpanish);
        set(8, hreflandForKorean);
        set(9, hreflandForJapanese);
    }
}
