/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import lorgNew.tables.Topics;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TopicsRecord extends UpdatableRecordImpl<TopicsRecord> implements Record9<Integer, String, String, String, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 178711700;

    /**
     * Setter for <code>lorgNew.topics.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lorgNew.topics.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lorgNew.topics.topic</code>.
     */
    public void setTopic(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lorgNew.topics.topic</code>.
     */
    public String getTopic() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lorgNew.topics.content</code>.
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lorgNew.topics.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lorgNew.topics.slug</code>.
     */
    public void setSlug(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lorgNew.topics.slug</code>.
     */
    public String getSlug() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lorgNew.topics.cropic</code>.
     */
    public void setCropic(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>lorgNew.topics.cropic</code>.
     */
    public String getCropic() {
        return (String) get(4);
    }

    /**
     * Setter for <code>lorgNew.topics.segment</code>.
     */
    public void setSegment(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>lorgNew.topics.segment</code>.
     */
    public String getSegment() {
        return (String) get(5);
    }

    /**
     * Setter for <code>lorgNew.topics.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>lorgNew.topics.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>lorgNew.topics.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>lorgNew.topics.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>lorgNew.topics.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>lorgNew.topics.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Topics.TOPICS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Topics.TOPICS.TOPIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Topics.TOPICS.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Topics.TOPICS.SLUG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Topics.TOPICS.CROPIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Topics.TOPICS.SEGMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Topics.TOPICS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Topics.TOPICS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Topics.TOPICS.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTopic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCropic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSegment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTopic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCropic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSegment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopicsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopicsRecord value2(String value) {
        setTopic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopicsRecord value3(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopicsRecord value4(String value) {
        setSlug(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopicsRecord value5(String value) {
        setCropic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopicsRecord value6(String value) {
        setSegment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopicsRecord value7(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopicsRecord value8(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopicsRecord value9(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopicsRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TopicsRecord
     */
    public TopicsRecord() {
        super(Topics.TOPICS);
    }

    /**
     * Create a detached, initialised TopicsRecord
     */
    public TopicsRecord(Integer id, String topic, String content, String slug, String cropic, String segment, String status, Timestamp created, Timestamp updated) {
        super(Topics.TOPICS);

        set(0, id);
        set(1, topic);
        set(2, content);
        set(3, slug);
        set(4, cropic);
        set(5, segment);
        set(6, status);
        set(7, created);
        set(8, updated);
    }
}
