/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.records;


import javax.annotation.Generated;

import lorgNew.tables.UserToFavorites;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserToFavoritesRecord extends UpdatableRecordImpl<UserToFavoritesRecord> implements Record6<Integer, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -1638212803;

    /**
     * Setter for <code>lorgNew.user_to_favorites.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lorgNew.user_to_favorites.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lorgNew.user_to_favorites.usid</code>.
     */
    public void setUsid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lorgNew.user_to_favorites.usid</code>.
     */
    public Integer getUsid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lorgNew.user_to_favorites.qsid</code>.
     */
    public void setQsid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lorgNew.user_to_favorites.qsid</code>.
     */
    public Integer getQsid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>lorgNew.user_to_favorites.answid</code>.
     */
    public void setAnswid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>lorgNew.user_to_favorites.answid</code>.
     */
    public Integer getAnswid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>lorgNew.user_to_favorites.usidfav</code>.
     */
    public void setUsidfav(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>lorgNew.user_to_favorites.usidfav</code>.
     */
    public Integer getUsidfav() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>lorgNew.user_to_favorites.topid</code>.
     */
    public void setTopid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>lorgNew.user_to_favorites.topid</code>.
     */
    public Integer getTopid() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserToFavorites.USER_TO_FAVORITES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserToFavorites.USER_TO_FAVORITES.USID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserToFavorites.USER_TO_FAVORITES.QSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return UserToFavorites.USER_TO_FAVORITES.ANSWID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return UserToFavorites.USER_TO_FAVORITES.USIDFAV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return UserToFavorites.USER_TO_FAVORITES.TOPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getQsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getAnswid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getUsidfav();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getTopid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getQsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAnswid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getUsidfav();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getTopid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserToFavoritesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserToFavoritesRecord value2(Integer value) {
        setUsid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserToFavoritesRecord value3(Integer value) {
        setQsid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserToFavoritesRecord value4(Integer value) {
        setAnswid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserToFavoritesRecord value5(Integer value) {
        setUsidfav(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserToFavoritesRecord value6(Integer value) {
        setTopid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserToFavoritesRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserToFavoritesRecord
     */
    public UserToFavoritesRecord() {
        super(UserToFavorites.USER_TO_FAVORITES);
    }

    /**
     * Create a detached, initialised UserToFavoritesRecord
     */
    public UserToFavoritesRecord(Integer id, Integer usid, Integer qsid, Integer answid, Integer usidfav, Integer topid) {
        super(UserToFavorites.USER_TO_FAVORITES);

        set(0, id);
        set(1, usid);
        set(2, qsid);
        set(3, answid);
        set(4, usidfav);
        set(5, topid);
    }
}
