/*
 * This file is generated by jOOQ.
*/
package lorgNew.tables.records;


import javax.annotation.Generated;

import lorgNew.tables.Votes;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VotesRecord extends UpdatableRecordImpl<VotesRecord> implements Record7<Integer, Integer, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 426657017;

    /**
     * Setter for <code>lorgNew.votes.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lorgNew.votes.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lorgNew.votes.qsid</code>.
     */
    public void setQsid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lorgNew.votes.qsid</code>.
     */
    public Integer getQsid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lorgNew.votes.answid</code>.
     */
    public void setAnswid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lorgNew.votes.answid</code>.
     */
    public Integer getAnswid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>lorgNew.votes.comid</code>.
     */
    public void setComid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>lorgNew.votes.comid</code>.
     */
    public Integer getComid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>lorgNew.votes.balance</code>.
     */
    public void setBalance(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>lorgNew.votes.balance</code>.
     */
    public Integer getBalance() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>lorgNew.votes.upvotes</code>.
     */
    public void setUpvotes(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>lorgNew.votes.upvotes</code>.
     */
    public Integer getUpvotes() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>lorgNew.votes.downvotes</code>.
     */
    public void setDownvotes(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>lorgNew.votes.downvotes</code>.
     */
    public Integer getDownvotes() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Votes.VOTES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Votes.VOTES.QSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Votes.VOTES.ANSWID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Votes.VOTES.COMID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Votes.VOTES.BALANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Votes.VOTES.UPVOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Votes.VOTES.DOWNVOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getQsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getAnswid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getComid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getUpvotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getDownvotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getQsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAnswid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getComid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getUpvotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getDownvotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotesRecord value2(Integer value) {
        setQsid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotesRecord value3(Integer value) {
        setAnswid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotesRecord value4(Integer value) {
        setComid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotesRecord value5(Integer value) {
        setBalance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotesRecord value6(Integer value) {
        setUpvotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotesRecord value7(Integer value) {
        setDownvotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotesRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VotesRecord
     */
    public VotesRecord() {
        super(Votes.VOTES);
    }

    /**
     * Create a detached, initialised VotesRecord
     */
    public VotesRecord(Integer id, Integer qsid, Integer answid, Integer comid, Integer balance, Integer upvotes, Integer downvotes) {
        super(Votes.VOTES);

        set(0, id);
        set(1, qsid);
        set(2, answid);
        set(3, comid);
        set(4, balance);
        set(5, upvotes);
        set(6, downvotes);
    }
}
